### ISSUE TITLE
Create downstream release script/tooling

### ISSUE THREAD

**Issue by maxamillion** [ansible-collections/community.okd#10]
##### SUMMARY

Need to create a downstream release script and make target.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Makefile

**Comment by maxamillion** [comment]
Depends on acceptance and release of downstream `kubernetes.base` https://github.com/ansible-collections/community.kubernetes/pull/197 https://github.com/ansible-collections/community.kubernetes/issues/195

**Comment by tima** [comment]
This was handled by PR #20. Closing.
