### ISSUE TITLE
Create Integrations Tests for the OpenShift Inventory Plugin

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#17]
##### SUMMARY

The openshift inventory plugin currently does not have any integration tests.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

plugins/inventory/openshift.py

##### ADDITIONAL INFORMATION

Somehow this plugin was accepted without proper integration tests. Go figure.

**Comment by fabianvf** [comment]
Done in #16
