### ISSUE TITLE
Figure out what to do with OpenShift tests

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.okd#2]
##### SUMMARY

Issue moved from: https://github.com/ansible-collections/community.kubernetes/issues/10

Currently, the tests run by `ansible-test` (e.g. `ansible-test integration --docker -v --color`) are running on OpenShift 3.9.0 (`openshift/origin:v3.9.0`), which has been out of support for some time.

The current release of OpenShift 3 is 3.11, though the Docker Hub image for that version is 2 years old (https://hub.docker.com/r/openshift/origin/tags), and also uses Kubernetes 1.11 as a base, which has not been supported upstream for some time either (see the [K8s version skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/)).

It would be good to use a supported image for the CI environment k8s cluster testing—for Operator SDK, the `bsycorp/kind` (see [tags](https://hub.docker.com/r/bsycorp/kind/tags)). There's also the official [SIG kind](https://kind.sigs.k8s.io), which I've successfully used on other ansible testing projects ([example](https://github.com/geerlingguy/ansible-for-kubernetes/blob/master/tests/cluster-aws-eks.sh#L32-L42)).

Ideally, we would have something from CRC or OKD that's equivalent to the single-container approach in `openshift/origin`, but I'm not sure if there's any timeline for something CI/local-friendly for OpenShift 4.x.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

tests / CI

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
cc @fabianvf

**Comment by fabianvf** [comment]
I'll try and wire us into the openshift prow instance github.com/openshift/release

**Comment by tima** [comment]
Falls under Meta-issue #5.

**Comment by geerlingguy** [comment]
@tima - I think we can close this issue. I'm going to open a new issue over in ansible/ansible to track pulling out the ansible-test integration point that we used to build a super old OpenShift container running on like 3.9.

I opened up https://github.com/ansible/ansible/issues/71383 to track that work in ansible/ansible upstream.
