### ISSUE TITLE
Add special handling to `k8s` module for OpenShift Template resources

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#22]
##### SUMMARY

OpenShift Template resources are reported to have "quirks" with how they are implemented in the APIs. To abstract users from having to deal with this, logic needs be added to the `k8s` module in this collection to handle Template resources as a developer would expect.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

plugins/modules/k8s.py

**Comment by fabianvf** [comment]
So it looks like I've fixed all the issues here already in the Python client, no changes needed in the modules AFAICT. Closing this for now, if anyone runs into a specific issue they can file an issue and we can fix it as normal, but Templates should work like every other resource.
