### ISSUE TITLE
Move k8s_auth module from community.kubernetes to here

### ISSUE THREAD

**Issue by geerlingguy** [ansible-collections/community.okd#28]
##### SUMMARY

The `k8s_auth` module that's currently part of the `community.kubernetes` collection is basically built for (and I believe only works with) OpenShift.

We can move that module into this repository since its maintenance and testing really needs to be done against an OpenShift cluster.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

k8s_auth

##### ADDITIONAL INFORMATION

N/A

**Comment by tima** [comment]
Related to ansible-collections/community.kubernetes#222.
