### ISSUE TITLE
`openshift_auth` molecule tests only work when run from a pod in the cluster

### ISSUE THREAD

**Issue by fabianvf** [ansible-collections/community.okd#35]
##### SUMMARY

The molecule tests for `openshift_auth` have the host hardcoded to `https://kubernetes.default.svc`, which is the fqdn for the API server when running as a pod in the cluster. We should make the task able to determine whether it's running incluster or not, and have it determine the proper host. Ideally, this can be done via the planned `community.kubernetes.k8s_cluster_info` module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

tests
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by alinabuzachis** [comment]
Hello @fabianvf, do you know if there is a way to solve this issue? If not, can we close this?

**Comment by fabianvf** [comment]
@alinabuzachis this should now be possible using the `connection.host` value returned by the `k8s_cluster_info` module https://github.com/ansible-collections/community.kubernetes/blob/main/plugins/modules/k8s_cluster_info.py#L64
