### ISSUE TITLE
Prepare for a 0.3.0 release

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#48]
##### SUMMARY

We'd like to release the 0.3.0 version of this collection.

We will need to go through past PRs and make sure they are all accounted for in changelog fragments, then I'll coordinate its release into Galaxy.

This release will serve as an "alpha" of 1.0.0.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

Releases

##### ADDITIONAL INFORMATION

N/A

**Comment by geerlingguy** [comment]
My own little checklist:

- [ ] Update galaxy.yml, the Makefile, and this README's requirements.yml example with the new version for the collection.
- [ ] Update the CHANGELOG (See #24 / README)
- [ ] Commit the changes and create a PR with the changes
- [ ] Merge that PR
- [ ] Tag the version in Git and push to GitHub
