### ISSUE TITLE
Setup OpenShift CI Testing

### ISSUE THREAD

**Issue by tima** [ansible-collections/community.okd#5]
Testing OpenShift functionality has additional and specialized requirements that goes beyond the standard Kubernetes CI testing. This meta-issue is to track establishing task for setting up the means of testing this collection's content against OpenShift. 

- [x] moving the existing openshift tests from community.kubernetes into molecule 
- [x] setup the OpenShift CI system (prow) for testing this collection

[More tasks likely to be added]

**Comment by geerlingguy** [comment]
First task has been done (though existing tests in community.kubernetes would also need cleaning up in a follow-up issue there—unrelated to this repo's work).

**Comment by tima** [comment]
@fabianvf Can this be closed out or are you leaving this open for something else?

**Comment by fabianvf** [comment]
Assumed moving it to done would close it

**Comment by tima** [comment]
I guess not. ¯\_(ツ)_/¯
