### ISSUE TITLE
Fix downstream script to not overwrite repo: and issues: keys in galaxy.yml

### ISSUE THREAD

**Issue by thedoubl3j** [ansible-collections/community.okd#65]
##### SUMMARY

The downstream script which changes somethings for the AH release overwrites the repo: key value, changing it to a repo that does not exist (redhat.openshift) when in fact, it should remain as the community.okd repo url. This also effects the issues: key name as well
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

downstream.sh
##### ANSIBLE VERSION

```paste below
n/a
```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

All environments affected

##### STEPS TO REPRODUCE

run the downstream script and it will change the key

##### EXPECTED RESULTS

repo url stays the same

##### ACTUAL RESULTS

repo key altered to https://github.com/ansible-collections/redhat.openshift/issues

**Comment by tima** [comment]
@thedoubl3j I'm going to close this because I noticed @geerlingguy listed this as one of the problems in the description of #57.
