### ISSUE TITLE
Unable to install the okd collection--> ERROR! Failed to find collection community.okd:0.1.0

### ISSUE THREAD

**Issue by ratripathi** [ansible-collections/community.okd#9]
##### SUMMARY
Unable to install the oks collection--> ERROR! Failed to find collection community.okd:0.1.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Requirements.yaml:

```
---
collections:
  - name: community.kubernetes
    version: 1.0.0
  - name: community.okd
    version: 0.1.0
```

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /Users/test/Documents/REPO/deployment-automation/ansible.cfg
  configured module search path = ['/Users/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.11/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 21 2020, 10:48:26) [Clang 11.0.3 (clang-1103.0.32.6

```

##### CONFIGURATION

```paste below

COLLECTIONS_PATHS(/Users/test/Documents/REPO/deployment-automation/ansible.cfg) = ['/Users/test/Documents/REPO/deployment-automation/collections']

```

##### OS / ENVIRONMENT

Mac OS Catalina

##### STEPS TO REPRODUCE

1. Add the okd dependency to the `requirements.yml ` file
2. Execute the following command--> `ansible-galaxy collection install -r requirements.yml `

##### EXPECTED RESULTS

The OKD collection should be installed:

##### ACTUAL RESULTS

```paste below
Process install dependency map
ERROR! Failed to find collection community.okd:0.1.0

```

**Comment by tima** [comment]
@ratripathi: We just setup this repo and haven't had anything to release so this is to be expected until that time.
